version: '3.9'
services:
  nodejs-server:
    build:
      context: ./src/back_end
    expose:
      - 3080
    ports:
      - 9229:9229
    container_name: node-api
    volumes:
       - ./src/back_end:/usr/src/app/api
       - /usr/src/app/api/node_modules
    depends_on:
      - redis
      - rabbitmq
  react-ui:
    build:
      context: ./src/front_end
    expose:
      - 3000 
    ports:
      - 3000:3000
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./src/front_end:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules
    depends_on:
      - nodejs-server
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:  
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - react-ui
      - nodejs-server
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'  
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  redis:
    image: redis
    container_name: 'redis' 
    ports:
      - 6379:6379
    expose:
      - 6379
  task-worker:
    container_name: task-worker
    build:
      context: ./src/task_worker
    depends_on:
      - rabbitmq
      - redis
    ports:
      - 5678:5678
    volumes:
      - ./src/resources:/usr/src/resources
